### ISSUE TITLE
auro-modal: Separate background opacity from modal state

### ISSUE THREAD

**Issue by clockeby** [AlaskaAirlines/auro-dialog#13] opened 2020-10-05 21:36 UTC
## Is your feature request related to a problem? Please describe.
The current state options for Auro modal (blocking or non-blocking) are tied to the opacity level used to darken the screen behind the modal. Darkening the entire screen by 20% feels excessive for a dialog telling you the seat has no window. A slight shadow would suffice for desktop and mobile to differentiate the modal overlay from the background content in this instance.

## Describe the solution you'd like
Can the dialog's state (non-blocking vs. blocking) be separated from the level of darkening scrim used behind it? State should still be used to determine available interaction options (an X to close vs. 'yes or no' button options, respectively). The opacity level for the background could have variable options for darker, lighter, or transparent (none) based on your specific use case with the modal/dialog drop shadow being set to the standard shadow level for cards and other overlays.

## Describe alternatives you've considered
An additional state option could be added. This would allow the darkest background option to be tied to the blocking state, the lightest tied to the non-blocking state, and a transparent background option to be added to the new state. I have not been able to come up with another other differentiator to address the functionality overlap between non-blocking and any new state.

## Additional context
Screenshot, Auro modal with transparent background and drop shadow.
![image](https://user-images.githubusercontent.com/9092702/95134609-0803ac00-0718-11eb-8e56-cbf9d3a846fe.png)

**Comment by diana-wang** [comment] 2020-10-07 01:12
Closing as this is a duplicate of #12

**Closed by diana-wang** 2020-10-07 01:12 UTC
Labels: Type: Feature
